2021-09-07 20:40:52,632 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 98, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-07 20:40:52,650 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 92, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-07 20:40:52,652 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 98, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-07 20:40:52,653 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 92, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-08 09:46:57,841 - CRITICAL - globalvar.py - could not open port 'COM3': FileNotFoundError(2, '系统找不到指定的文件。', None, 2)
Traceback (most recent call last):
  File "F:\pyside2\bin\globalvar.py", line 18, in <module>
    fix_serial = SerialPort('COM3', 1115200)
  File "F:\pyside2\sokets\serialport.py", line 21, in __init__
    self.ser = Serial(port, baudrate=baudRate, write_timeout=write_timeout, timeout=timeout, bytesize=EIGHTBITS,
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Python38\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': FileNotFoundError(2, '系统找不到指定的文件。', None, 2)
2021-09-08 09:46:59,265 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 99, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-08 09:46:59,266 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 93, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-08 09:46:59,267 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 99, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-08 09:46:59,268 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 93, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-08 09:47:38,630 - CRITICAL - globalvar.py - could not open port 'COM3': FileNotFoundError(2, '系统找不到指定的文件。', None, 2)
Traceback (most recent call last):
  File "F:/pyside2/bin/globalvar.py", line 19, in <module>
    fix_serial = SerialPort('COM3', 1115200)
  File "F:\pyside2\sokets\serialport.py", line 21, in __init__
    self.ser = Serial(port, baudrate=baudRate, write_timeout=write_timeout, timeout=timeout, bytesize=EIGHTBITS,
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Python38\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': FileNotFoundError(2, '系统找不到指定的文件。', None, 2)
2021-09-08 09:49:42,267 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 99, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-08 09:49:42,269 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 93, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-08 09:49:42,270 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 99, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-08 09:49:42,271 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 93, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-08 09:52:50,135 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 99, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-08 09:52:50,136 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 93, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-08 09:52:50,136 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 99, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-08 09:52:50,136 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 93, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-08 11:48:34,577 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 99, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-08 11:48:34,588 - CRITICAL - step.py - run_step Exception！！'MesMac'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 93, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'MesMac'
2021-09-08 11:48:34,589 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 193, in run_step
    self.test_command = self.ComdSend
  File "F:\pyside2\model\step.py", line 99, in test_command
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
2021-09-08 11:48:34,589 - CRITICAL - step.py - run_step Exception！！'SN'
Traceback (most recent call last):
  File "F:\pyside2\model\step.py", line 194, in run_step
    self.test_spec = self.Spec
  File "F:\pyside2\model\step.py", line 93, in test_spec
    value = re.compile(f'<{a}>').sub(globals()[a], value, count=1)
KeyError: 'SN'
